### ISSUE TITLE
Midi Router server with a default config

### ISSUE THREAD

**Issue by ludovic-lambert** [shemeshg/RtMidiWrap#4]
Hi Shemeshg,
I've installed your Midi Router to forward MIDI messages from one Audio interface to another on my computer.
It works like a charm, so thank you so much.
However I don't get how to run the server with a default preset without having to recreate the config at each run.
Do you have any documentation?
If not, how can I achieve this?
Thank you !
Cheers
Ludo

**Comment by shemeshg** [comment]
Hi

Your asking two questions, 

## 1. How to load and save config?

- Select presets from Tab
- At the upload config select "choose file"
![image](https://user-images.githubusercontent.com/8200598/228977340-15fa296e-e48f-4388-a7e6-cb7d2620f654.png)


![image](https://user-images.githubusercontent.com/8200598/228975460-5525e781-9f9f-4505-afb0-4af1f99c4c99.png)

## 2. Do I have an option to have "Default" config, that will be loaded when I start the app?

- The config might contain specific settings for your client.
(JsMidi routing, or Preset selection)
- It might be that multiple client serves one server, or client refers to multiple servers.

So the question for now is No (Because it will have to be unique per server, and per client), but if it is important maybe we can think of something that can make sense.

# So
1. did you meant for 1. or 2 ?
2. Don't recreate the config, you can download and upload it.
3. No documentation, but I am happy to answer any question you have

**Comment by ludovic-lambert** [comment]
Hi shemeshg. Thank you for your answer. I had like to run a "midi router server.exe" -config myconfigfile at Windows startup. I understand I can't. Too bad. That won't prevent me from using it, I'll just reload the config file each time.
You did a great job on routing, and that's the most important part.

**Comment by shemeshg** [comment]
The server itself has no parser, it just accept routing configuration commands.

The benefit of that was stability, and fast development at the electron part that parse the config into server commands.
at that days I believed c++ should be kept minimal.

See example: https://github.com/shemeshg/qwebchannelTypeScriptExample/blob/cc49b155a8e5ed8772ebb0d5464e697705278af0/src/main.ts#L74

 
Today I think writing everything in modern c++  might actually be a good thing,
